- name: Add key to system
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  
- name: Add entry to /etc/apt/sources.list
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' update_cache=yes
    
- name: Install Jenkins
  apt: name=jenkins state=latest